Dev java
LINVAST/LINVAST pull request #3
Opened 2021-08-05 09:28 UTC by marijakatic

Declarations Java AST Builder and tests.

2021-08-07 21:00 UTC, ivan-ristovic requested changes
This is excellent! The code is extremely readable and precise! 

I have added a few comments, most of them regarding the stylepoints, I would suggest running automatic formatting from within Visual Studio, it will use formatting rules from `.editorconfig` so you will probably fix most of my comments just by running that.

Thank you for the excellent work! :)

2021-08-08 21:01 UTC, marijakatic commented on LINVAST.Imperative/Builders/Java/JavaASTBuilder.Declarations.cs
> +        // package and import declarations:
Wow, great, thank you!

2021-08-08 21:05 UTC, marijakatic commented on LINVAST.Imperative/Nodes/Common/Modifiers.cs
> +        Final = 16,
Ok. I fixed it. :)

2021-08-08 21:17 UTC, marijakatic commented on LINVAST.Tests/Imperative/Builders/Java/InterfaceDeclarationTests.cs
> +            StringAssert.IsMatch(@"Interface1\s*{\s*}\s*", ast1.GetText());
Great remark. I should have thought about that.
Thank you! :)

2021-08-08 22:04 UTC, ivan-ristovic approved these changes
LGTM, waiting for others to do their work and we can merge.

2021-09-12 09:33 UTC, merged